export const navigation = [
  { label: 'Services', href: '#services' },
  { label: 'Portfolio', href: '#portfolio' },
  { label: 'Catalog', href: '#catalog' },
  { label: 'Journal', href: '#journal' },
  { label: 'Contact', href: '#consultation' },
];

export const adminTabs = [
  { id: 'overview', label: 'Overview' },
  { id: 'content', label: 'Content' },
  { id: 'services', label: 'Services' },
  { id: 'projects', label: 'Portfolio' },
  { id: 'products', label: 'Catalog' },
  { id: 'bookings', label: 'Bookings' },
  { id: 'inquiries', label: 'Inquiries' },
  { id: 'reviews', label: 'Reviews' },
  { id: 'users', label: 'Users' },
  { id: 'blogs', label: 'Blogs' },
  { id: 'notifications', label: 'Notifications' },
  { id: 'settings', label: 'Settings' },
  { id: 'reports', label: 'Reports' },
  { id: 'superadmin', label: 'Super Admin' },
];

export const collectionConfigs = {
  services: {
    title: 'Service Management',
    endpoint: 'services',
    responseOne: 'service',
    createLabel: 'Add service',
    emptyItem: {
      name: '',
      category: '',
      description: '',
      timeline: '',
      price: '',
      featured: false,
    },
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'category', label: 'Category' },
      { key: 'timeline', label: 'Timeline' },
      { key: 'price', label: 'Price' },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'featured', label: 'Featured', type: 'checkbox' },
    ],
  },
  projects: {
    title: 'Portfolio Management',
    endpoint: 'projects',
    responseOne: 'project',
    createLabel: 'Add project',
    emptyItem: {
      title: '',
      category: '',
      location: '',
      description: '',
      imageUrl: '/brand/a4.jpeg',
      videoUrl: '',
      featured: false,
    },
    fields: [
      { key: 'title', label: 'Title' },
      { key: 'category', label: 'Category' },
      { key: 'location', label: 'Location' },
      { key: 'imageUrl', label: 'Image URL' },
      { key: 'videoUrl', label: 'Video URL' },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'featured', label: 'Featured', type: 'checkbox' },
    ],
  },
  products: {
    title: 'Catalog Management',
    endpoint: 'products',
    responseOne: 'product',
    createLabel: 'Add product',
    emptyItem: {
      name: '',
      category: '',
      material: '',
      specification: '',
      price: 0,
      imageUrl: '/brand/a3.jpeg',
      swatch: 'linear-gradient(135deg, #b9b0a1, #f1ece1)',
      featured: false,
    },
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'category', label: 'Category' },
      { key: 'material', label: 'Material' },
      { key: 'price', label: 'Price', type: 'number' },
      { key: 'imageUrl', label: 'Image URL' },
      { key: 'swatch', label: 'Swatch CSS' },
      { key: 'specification', label: 'Specification', type: 'textarea' },
      { key: 'featured', label: 'Featured', type: 'checkbox' },
    ],
  },
  blogs: {
    title: 'Blog Publishing',
    endpoint: 'blogs',
    responseOne: 'blog',
    createLabel: 'Add blog',
    emptyItem: {
      title: '',
      excerpt: '',
      published: false,
    },
    fields: [
      { key: 'title', label: 'Title' },
      { key: 'excerpt', label: 'Excerpt', type: 'textarea' },
      { key: 'published', label: 'Published', type: 'checkbox' },
    ],
  },
  notifications: {
    title: 'Notification Management',
    endpoint: 'notifications',
    responseOne: 'notification',
    createLabel: 'Add notification',
    emptyItem: {
      title: '',
      channel: 'email',
      body: '',
      active: true,
    },
    fields: [
      { key: 'title', label: 'Title' },
      { key: 'channel', label: 'Channel' },
      { key: 'body', label: 'Body', type: 'textarea' },
      { key: 'active', label: 'Active', type: 'checkbox' },
    ],
  },
  superadmin: {
    title: 'Super Admin User & Admin Manager',
    endpoint: 'users',
    responseOne: 'user',
    createLabel: 'Add New Admin or User',
    emptyItem: {
      name: '',
      email: '',
      password: '',
      phone: '',
      role: 'admin',
      status: 'active',
    },
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'email', label: 'Email' },
      { key: 'password', label: 'Password', type: 'text' },
      { key: 'phone', label: 'Phone' },
      { key: 'role', label: 'Role (admin/user/superadmin)' },
      { key: 'status', label: 'Status (active/suspended)' },
    ],
  },
};
