export const navigation = [
  { label: "Services", href: "#services" },
  { label: "Portfolio", href: "#portfolio" },
  { label: "Catalog", href: "#catalog" },
  { label: "Journal", href: "#journal" },
  { label: "Contact", href: "#consultation" },
];

export const adminTabs = [
  { id: "overview", label: "Overview" },
  { id: "content", label: "Content" },
  { id: "services", label: "Services" },
  { id: "projects", label: "Portfolio" },
  { id: "products", label: "Catalog" },
  { id: "bookings", label: "Bookings" },
  { id: "inquiries", label: "Inquiries" },
  { id: "reviews", label: "Reviews" },
  { id: "users", label: "Users" },
  { id: "blogs", label: "Blogs" },
  { id: "notifications", label: "Notifications" },
  { id: "settings", label: "Settings" },
  { id: "reports", label: "Reports" },
  { id: "superadmin", label: "Super Admin" },
];

export const collectionConfigs = {
  services: {
    collection: "services",
    title: "Service Management",
    createLabel: "Add Service",
    emptyItem: {
      name: "",
      category: "",
      description: "",
      timeline: "",
      price: "",
      featured: false,
      createdAt: Date.now(),
    },
    fields: [
      { key: "name", label: "Name" },
      {
        key: "category",
        label: "Category",
        type: "select",
        required: true,
        options: [
          "Soft Furnishing",
          "Shading Solutions",
          "Wall Finishes",
          "Surface Styling",
          "Furniture",
          "Turnkey Design",
        ],
      },
      {
        key: "timeline",
        label: "Timeline",
        type: "select",
        options: ["3-7 days", "4-8 days", "5-10 days", "1-2 weeks", "2-4 weeks", "Project based"],
      },
      { key: "price", label: "Budget / Starting Price" },
      { key: "description", label: "Description", type: "textarea" },
      { key: "featured", label: "Featured", type: "checkbox" },
    ],
  },

  projects: {
    collection: "projects",
    title: "Portfolio Management",
    createLabel: "Add Project",
    emptyItem: {
      title: "",
      category: "",
      location: "",
      description: "",
      imageUrl: "",
      videoUrl: "",
      featured: false,
      createdAt: Date.now(),
    },
    fields: [
      { key: "title", label: "Title" },
      {
        key: "category",
        label: "Category",
        type: "select",
        required: true,
        options: ["Curtains", "Wallpapers", "Flooring", "Furniture", "Blinds"],
      },
      { key: "location", label: "Location" },
      { key: "imageUrl", label: "Project Image", type: "image" },
      { key: "videoUrl", label: "Video URL" },
      { key: "description", label: "Description", type: "textarea" },
      { key: "featured", label: "Featured", type: "checkbox" },
    ],
  },

  products: {
    collection: "products",
    title: "Catalog Management",
    createLabel: "Add Product",
    emptyItem: {
      name: "",
      category: "",
      material: "",
      specification: "",
      price: 0,
      imageUrl: "",
      swatch: "",
      featured: false,
      createdAt: Date.now(),
    },
    fields: [
      { key: "name", label: "Name" },
      {
        key: "category",
        label: "Category",
        type: "select",
        required: true,
        options: ["Furniture", "Decor", "Blinds", "Lighting", "Flooring"],
      },
      { key: "material", label: "Material" },
      { key: "price", label: "Price", type: "number" },
      { key: "imageUrl", label: "Product Image", type: "image" },
      { key: "swatch", label: "Swatch" },
      { key: "specification", label: "Specification", type: "textarea" },
      { key: "featured", label: "Featured", type: "checkbox" },
    ],
  },

  blogs: {
    collection: "blogs",
    title: "Advanced Blog Management",
    createLabel: "Add Blog",
    emptyItem: {
      title: "",
      category: "",
      author: "",
      coverImage: "",
      excerpt: "",
      content: "",
      readTime: "",
      tags: "",
      published: false,
      featured: false,
      createdAt: Date.now(),
    },
    fields: [
      { key: "title", label: "Title" },
      {
        key: "category",
        label: "Category",
        type: "select",
        required: true,
        options: ["Design Tips", "Curtains", "Blinds", "Wallpaper", "Furniture", "Project Guide"],
      },
      { key: "author", label: "Author" },
      { key: "coverImage", label: "Cover Image", type: "image" },
      { key: "readTime", label: "Read Time" },
      { key: "tags", label: "Tags" },
      { key: "excerpt", label: "Excerpt", type: "textarea" },
      { key: "content", label: "Full Article / Notes", type: "textarea" },
      { key: "published", label: "Published", type: "checkbox" },
      { key: "featured", label: "Featured", type: "checkbox" },
    ],
  },

  notifications: {
    collection: "notifications",
    title: "Advanced Notifications",
    createLabel: "Add Notification",
    emptyItem: {
      title: "",
      channel: "email",
      audience: "all",
      trigger: "manual",
      priority: "normal",
      status: "draft",
      scheduledFor: "",
      body: "",
      ctaLabel: "",
      ctaUrl: "",
      active: true,
      createdAt: Date.now(),
    },
    fields: [
      { key: "title", label: "Title" },
      {
        key: "channel",
        label: "Channel",
        type: "select",
        options: [
          { value: "email", label: "Email" },
          { value: "sms", label: "SMS" },
          { value: "whatsapp", label: "WhatsApp" },
          { value: "dashboard", label: "Dashboard" },
        ],
      },
      {
        key: "audience",
        label: "Audience",
        type: "select",
        options: [
          { value: "all", label: "All clients" },
          { value: "new-leads", label: "New leads" },
          { value: "booked-clients", label: "Booked clients" },
          { value: "admins", label: "Admins only" },
        ],
      },
      {
        key: "trigger",
        label: "Trigger",
        type: "select",
        options: [
          { value: "manual", label: "Manual" },
          { value: "booking-created", label: "New booking" },
          { value: "inquiry-created", label: "New inquiry" },
          { value: "quote-ready", label: "Quote ready" },
        ],
      },
      {
        key: "priority",
        label: "Priority",
        type: "select",
        options: [
          { value: "low", label: "Low" },
          { value: "normal", label: "Normal" },
          { value: "high", label: "High" },
          { value: "urgent", label: "Urgent" },
        ],
      },
      {
        key: "status",
        label: "Status",
        type: "select",
        options: [
          { value: "draft", label: "Draft" },
          { value: "scheduled", label: "Scheduled" },
          { value: "sent", label: "Sent" },
          { value: "paused", label: "Paused" },
        ],
      },
      { key: "scheduledFor", label: "Scheduled Date", type: "date" },
      { key: "body", label: "Body", type: "textarea" },
      { key: "ctaLabel", label: "Action Label" },
      { key: "ctaUrl", label: "Action URL", type: "url" },
      { key: "active", label: "Active", type: "checkbox" },
    ],
  },

  superadmin: {
    collection: "users",
    title: "User Management",
    createLabel: "Add User",
    emptyItem: {
      name: "",
      email: "",
      password: "",
      phone: "",
      role: "admin",
      status: "active",
      createdAt: Date.now(),
    },
    fields: [
      { key: "name", label: "Name" },
      { key: "email", label: "Email" },
      { key: "phone", label: "Phone" },
      {
        key: "role",
        label: "Role",
      },
      {
        key: "status",
        label: "Status",
      },
    ],
  },
};
